### ISSUE TITLE
Zabbix.API.call with Custom Timeout option

### ISSUE THREAD

**Issue by kgrvamsi** [abanichev/zabbix#1]
Can we have a custom timeout option to query a specific call to zabbix api?

**Comment by abanichev** [comment]
@kgrvamsi you can now use `:timeout` option like this:

```elixir
iex> Zabbix.API.call("some.method", %{param: "value"}, timeout: 10)
{:error, :timeout}
```

I will update the package/docs in Hex soon 💜

**Comment by kgrvamsi** [comment]
Hello @abanichev Thanks for the response and when i use the following way i see the following error.

```
iex(4)> Zabbix.API.call("alert.get", timeout: 10)
{:error,
 {Tesla.Middleware.JSON, :encode,
  %Protocol.UndefinedError{
    description: "Jason.Encoder protocol must always be explicitly implemented",
    protocol: Jason.Encoder,
    value: {:timeout, 10}
  }}}
```

**Comment by abanichev** [comment]
Hi @kgrvamsi! If you need to call a method without params, just pass an empty map (`%{}`) in second argument.

```elixir
iex> Zabbix.API.call("alert.get", %{}, timeout: 10)
```

Please note:
1. Timeout is in milliseconds, so to set it to 1 second, you need to pass `timeout: 1000`;
2. `alert.get` without filters can return enormous amount of alerts in production or even crash Zabbix Server resulting in HTTP 500 status code in response.

**Comment by kgrvamsi** [comment]
Thanks for the info @abanichev will look into the documentation for more info on the filters and definitely don't want to crash the production zabbix server ...lol

**Comment by abanichev** [comment]
@kgrvamsi by "crashing" i dont mean it will stop working. It just will return you HTTP 500 error instead of result :)
